# image: registry.gitlab.com/pipeline-components/ansible-lint:latest
image: debian:bullseye

before_script:
  - apt-get update
  - apt-get install -y python-is-python3 python3-pip shellcheck
  - pip install ansible ansible-lint
  - ansible-lint --version

stages:
  - linter

ansible-lint:
  stage: linter
  tags:
    - debian
  script:
    - ansible-lint --show-relpath

shellcheck:
  stage: linter
  tags:
    - debian
  script:
    - >
      ansible -vvvv localhost -c local -m template -a "src=templates/config/ca-config-updater.sh.j2 dest=./ca-config-updater.sh" --extra-vars='{"item": {"name": "toto", "minTLSCertDuration": "1440h0m0s", "maxTLSCertDuration": "2160h0m0s", "defaultTLSCertDuration": "2160h0m0s"}, "step_ca_jwk_RAs_dir": "step", "step_ca_structure" : { "rootCA" : {"fqdn" : "ca.example.net"}}}'
    - cat ca-config-updater.sh | shellcheck -a -Cauto -f tty -o all -s bash -S style -x -- -