---
### Pre-Installation
- name: "Download Debian package version {{ step_ca_version }} "
  ansible.builtin.get_url:
    url: "{{ step_ca_url_deb }}"
    dest: "{{ step_ca_tmp_dir }}/{{ step_ca_deb }}"
    mode: '0640'
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

### Installation
- name: "Be sure step-ca version is installed (APT based): ({{ step_ca_version }})"
  ansible.builtin.apt:
    deb: "{{ step_ca_tmp_dir }}/{{ step_ca_deb }}"
    state: "{{ step_ca_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
