---
### Pre-Installation
- name: "Download latest Debian package of step-ca"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_deb }}"
    dest: "{{ stepcli_tmp_dir }}/step-ca_{{ step_ca_arch }}.deb"
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

### Installation
- name: "Be sure step-ca version ({{ step_ca_version }}) is installed (APT based)"
  ansible.builtin.apt:
    deb: "{{ stepca_tmp_dir }}/{{ stepca_apt_packages }}"
    state: "{{ stepca_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
