---
### Pre-Installation
- name: "Download Debian package version {{ step_ca_version }} "
  ansible.builtin.get_url:
    url: "{{ step_ca_url_deb }}"
    dest: "{{ step_ca_tmp_dir }}/step-ca_{{ step_ca_version }}.deb"
    mode: '0640'
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

### Installation
- name: "Be sure step-ca version is installed (APT based): ({{ step_ca_version }})"
  ansible.builtin.apt:
    deb: "{{ step_ca_tmp_dir }}/step-ca_{{ step_ca_version }}.deb"
    state: "{{ step_ca_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

### Gather facts
- name: "Gathering facts : Is step-ca service already present on the system"
  ansible.builtin.service_facts:
  tags:
    - install

- name: "Download step-ca systemd service file"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_systemd_svc_file }}"
    dest: "{{ step_ca_tmp_dir }}/step-ca.service"
    mode: '0644'
  environment: "{{ proxy_env }}"
  when: "'step-ca.service' not in services"
  check_mode: false
  tags:
    - install

- name: "Copy step-ca systemd service file to {{ step_ca_systemd_svc_file }}"
  ansible.builtin.copy:
    src: "{{ step_ca_tmp_dir }}/step-ca.service"
    dest: "{{ step_ca_systemd_svc_file }}"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_group }}"
    mode: '0644'
    remote_src: true
  when: "'step-ca.service' not in services"
  become: true
  notify:
    - Systemd daemon-reload
  tags:
    - install

### Cleaning install files
- name: "Clean temporary systemd service file in {{ step_ca_tmp_dir }}"
  ansible.builtin.file:
    name: "{{ step_ca_tmp_dir }}/step-ca.service"
    state: absent
  when: "'step-ca.service' not in services"
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
