---
### Pre-Installation
- name: "Download Debian package version {{ step_ca_version }} of step-ca"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_deb }}"
    dest: "{{ step_ca_tmp_dir }}/step-ca_{{ step_ca_arch }}.deb"
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

### Installation
- name: "Be sure step-ca version ({{ step_ca_version }}) is installed (APT based)"
  ansible.builtin.apt:
    deb: "{{ step_ca_tmp_dir }}/{{ step_ca_apt_packages }}"
    state: "{{ step_ca_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

- name: "Download step-ca systemd service file"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_systemd_svc_file }}"
    dest: "{{ step_ca_tmp_dir }}/step-ca.service"
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

- name: "Copy step-ca systemd service file to {{ step_ca_systemd_svc_file }}"
  ansible.builtin.copy:
    src: "{{ step_ca_tmp_dir }}/step-ca.service"
    dest: "{{ step_ca_systemd_svc_file }}"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_group }}"
    mode: '0644'
    remote_src: true
  become: true
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
