---
# - name: "Handling YubyHSM in step-ca role"
#   ansible.builtin.import_tasks: yubihsm.yml
#   when: step_ca_yubihsm
#   tags:
#     - step-ca

- name: "Handling step and step-ca role"
  ansible.builtin.import_tasks: step-ca.yml
  tags:
    - step-ca
