---
### Gather facts
- name: "Gathering facts : already installed ?"
  ansible.builtin.stat:
    path: "{{ step_ca_bin_file }}"
  check_mode: false
  register: installed
  tags:
    - install

### Prepare
- name: "Download step-ca source tarball version {{ step_ca_version }}"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_manual }}"
    dest: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    mode: '0640'
    validate_certs: true
  check_mode: false
  environment: "{{ proxy_env }}"
  # when: step_ca_version != "absent" and not srcpresent.stat.exists
  when: not installed.stat.exists
  tags:
    - install

- name: "Extract tarball to directory {{ step_ca_tmp_dir }}"
  ansible.builtin.unarchive:
    src: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    dest: "{{ step_ca_tmp_dir }}/"
    remote_src: true
    keep_newer: true
#  when: step_ca_version != "absent" and not srcpresent.stat.exists
  when: not installed.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - install

### Build
# https://github.com/smallstep/certificates/blob/master/CONTRIBUTING.md#build-step-ca-using-cgo
# sudo apt install golang -t bookworm-backports

- name: "Let's prepare build"
  ansible.builtin.command:
    cmd: make bootstrap
    chdir: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
  when: not installed.stat.exists
  register: step_ca_make_bootstrap_output
  changed_when: step_ca_make_bootstrap_output.rc != 0
  tags:
    - install

- name: "Let's build"
  ansible.builtin.command:
    cmd: make build GO_ENVS="CGO_ENABLED=1"
    chdir: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
  when: not installed.stat.exists
  register: step_ca_make_build_output
  changed_when: step_ca_make_build_output.rc != 0
  tags:
    - install

### Installation
- name: "Copy step-ca binary to {{ step_ca_bin_file }}"
  ansible.builtin.copy:
    src: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}/bin/step-ca"
    dest: "{{ step_ca_bin_file }}"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_group }}"
    mode: '0755'
    remote_src: true
  when: not installed.stat.exists
  become: true
  tags:
    - install

- name: "Copy step-ca systemd service file to {{ step_ca_systemd_svc_file }}"
  ansible.builtin.copy:
    src: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}/systemd/step-ca.service"
    dest: "{{ step_ca_systemd_svc_file }}"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_group }}"
    mode: '0644'
    remote_src: true
  when: not installed.stat.exists
  become: true
  notify:
    - Systemd daemon-reload
  tags:
    - install

- name: "Update systemd service file in order to use correct binary path ({{ step_ca_bin_file }})"
  ansible.builtin.replace:
    path: "{{ step_ca_systemd_svc_file }}"
    regexp: '/usr/bin/step-ca'
    replace: "{{ step_ca_bin_file }}"
  when: not installed.stat.exists
  become: true
  notify:
    - Systemd daemon-reload

### Cleaning install files
- name: "Clean tarball in {{ step_ca_tmp_dir }}"
  ansible.builtin.file:
    name: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    state: absent
  when: not installed.stat.exists
  tags:
    - install

# - name: "Clean directory in {{ step_ca_tmp_dir }}"
#   ansible.builtin.file:
#     name: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
#     state: absent
#   tags:
#     - install
