---
### Prepare
- name: "Download step-ca source tarball version {{ step_ca_version }}"
  ansible.builtin.get_url:
    url: "{{ step_ca_url_manual }}"
    dest: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    mode: '0640'
    validate_certs: true
  environment: "{{ proxy_env }}"
  # when: step_ca_version != "absent" and not srcpresent.stat.exists
  tags:
    - install

- name: "Extract tarball to directory {{ step_ca_tmp_dir }}"
  ansible.builtin.unarchive:
    src: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    dest: "{{ step_ca_tmp_dir }}/"
    remote_src: true
    keep_newer: true
#  when: step_ca_version != "absent" and not srcpresent.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - install

### Build
# https://github.com/smallstep/certificates/blob/master/CONTRIBUTING.md#build-step-ca-using-cgo
#sudo apt install golang -t bookworm-backports

- name: "Let's prepare build"
  ansible.builtin.shell:
    cmd: make bootstrap
    chdir: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
  tags:
    - install

- name: "Let's build"
  ansible.builtin.shell:
    cmd: make build GO_ENVS="CGO_ENABLED=1"
    chdir: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
  tags:
    - install

### Installation
- name: "Copy step-ca binary to {{ step_ca_bin_file }}"
  ansible.builtin.copy:
    src: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}/bin/step-ca"
    dest: "{{ step_ca_bin_file }}"
    owner: "{{ step_ca_user }}"
    group: "{{ step_ca_group }}"
    mode: '0644'
    remote_src: true
  become: true

### Cleaning install files
- name: "Clean tarball in {{ step_ca_tmp_dir }}"
  ansible.builtin.file:
    name: "{{ step_ca_tmp_dir }}/{{ step_ca_tarball_manual }}"
    state: absent
  tags:
    - install

# - name: "Clean directory in {{ step_ca_tmp_dir }}"
#   ansible.builtin.file:
#     name: "{{ step_ca_tmp_dir }}/certificates-{{ step_ca_version }}"
#     state: absent
#   tags:
#     - install
